import { type NextPage } from "next";
import Head from "next/head";
import Link from "next/link";
import { signIn, signOut, useSession } from "next-auth/react";
import { useRouter } from "next/router";

import { api } from "../utils/api";

const Home: NextPage = () => {
  const hello = api.example.hello.useQuery({ text: "from tRPC" });
  return (
    <>
      <Head>
        <title>Speech Simulator</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className="flex min-h-screen flex-col items-center justify-center bg-white">
        <AuthShowcase />
      </main>
    </>
  );
};

export default Home;

const AuthShowcase: React.FC = () => {
  const { data: sessionData } = useSession();

  const { data: secretMessage } = api.example.getSecretMessage.useQuery(
    undefined, // no input
    { enabled: sessionData?.user !== undefined }
  );

  const router = useRouter();
  const navigate = (path: string) => {
    if (router.pathname !== path) {
      router.push(path);
    }
  };

  // {sessionData && <span>Logged in as {sessionData.user?.name}</span>}

  return (
    <div className="flex flex-col items-center">
      <h1 className="p-16 text-5xl font-extrabold">Speech Simulator</h1>
      <div className="flex justify-around text-3xl">
        <button
          className="mx-2 w-80 rounded-xl bg-accent p-2 text-white"
          onClick={() => navigate("/presentations/create")}
        >
          Create Presentation
        </button>
        <button
          className="mx-2 w-80 rounded-xl bg-accent p-2 text-white"
          onClick={() => navigate("/presentations")}
        >
          Previous Presentations
        </button>
        <button className="mx-2 w-80 rounded-xl bg-accent p-2 text-white">
          Logout
        </button>
      </div>
      <i className="p-4">
        {sessionData && <span>Logged in as {sessionData.user?.name}</span>}
      </i>
    </div>
  );
};
