import { type NextPage } from "next";
import Head from "next/head";
import Link from "next/link";
import { signIn, signOut, useSession } from "next-auth/react";

import { api } from "../utils/api";

const Home: NextPage = () => {
  const hello = api.example.hello.useQuery({ text: "from tRPC" });
  return (
    <>
      <Head>
        <title>Speech Simulator</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className="flex min-h-screen flex-col items-center justify-center bg-white">
        <AuthShowcase />
      </main>
    </>
  );
};

export default Home;

const AuthShowcase: React.FC = () => {
  const { data: sessionData } = useSession();

  const { data: secretMessage } = api.example.getSecretMessage.useQuery(
    undefined, // no input
    { enabled: sessionData?.user !== undefined }
  );

  // {sessionData && <span>Logged in as {sessionData.user?.name}</span>}

  return (
    <div className="flex flex-col items-center">
      <h1 className="text-5xl">Speech Simulator</h1>
      <div className="flex justify-around text-3xl">
        <button className="mx-2 w-80 rounded-xl bg-accent p-2 text-white">
          Create Presentation
        </button>
        <button className="mx-2 w-80 rounded-xl bg-accent p-2 text-white">
          Previous Presentations
        </button>
        <button className="mx-2 w-80 rounded-xl bg-accent p-2 text-white">
          Logout
        </button>
      </div>
      <i>{sessionData && <span>Logged in as {sessionData.user?.name}</span>}</i>
    </div>
  );
};
